"""remove_api_key_secret

Revision ID: 01773233c655
Revises: 20251113_184044
Create Date: 2026-01-01 11:30:52.664533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01773233c655'
down_revision: Union[str, None] = '20251113_184044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'secret')
    op.drop_constraint(op.f('uq_chatbot_configs_tenant_name'), 'chatbot_configs', type_='unique')
    # op.create_unique_constraint('uq_conversation_document', 'conversation_documents', ['conversation_id', 'document_id'])
    op.alter_column('daily_token_usage', 'input_token_cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment='Cost for input tokens in USD',
               existing_nullable=True)
    op.alter_column('daily_token_usage', 'output_token_cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment='Cost for output tokens in USD',
               existing_nullable=True)
    op.alter_column('daily_token_usage', 'cache_token_cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment='Cost for cache tokens in USD',
               existing_nullable=True)
    op.alter_column('daily_token_usage', 'total_cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment='Total cost in USD',
               existing_nullable=True)
    op.alter_column('llm_models', 'input_token_price',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               comment='Price per 1M input tokens',
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('llm_models', 'output_token_price',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               comment='Price per 1M output tokens',
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('llm_models', 'cache_token_price',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               comment='Price per 1M cache tokens',
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('messages', 'input_tokens',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('messages', 'output_tokens',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('messages', 'total_tokens',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('monthly_billing', 'input_token_cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment='Cost for input tokens in USD',
               existing_nullable=False)
    op.alter_column('monthly_billing', 'output_token_cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment='Cost for output tokens in USD',
               existing_nullable=False)
    op.alter_column('monthly_billing', 'cache_token_cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment='Cost for cache tokens in USD',
               existing_nullable=False)
    op.alter_column('monthly_billing', 'total_cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment='Total cost for the month in USD',
               existing_nullable=False)
    op.alter_column('monthly_billing', 'avg_input_token_price',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               comment='Average price per 1M input tokens',
               existing_nullable=True)
    op.alter_column('monthly_billing', 'avg_output_token_price',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               comment='Average price per 1M output tokens',
               existing_nullable=True)
    op.alter_column('monthly_billing', 'avg_cache_token_price',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               comment='Average price per 1M cache tokens',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monthly_billing', 'avg_cache_token_price',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               comment=None,
               existing_comment='Average price per 1M cache tokens',
               existing_nullable=True)
    op.alter_column('monthly_billing', 'avg_output_token_price',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               comment=None,
               existing_comment='Average price per 1M output tokens',
               existing_nullable=True)
    op.alter_column('monthly_billing', 'avg_input_token_price',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               comment=None,
               existing_comment='Average price per 1M input tokens',
               existing_nullable=True)
    op.alter_column('monthly_billing', 'total_cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment=None,
               existing_comment='Total cost for the month in USD',
               existing_nullable=False)
    op.alter_column('monthly_billing', 'cache_token_cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment=None,
               existing_comment='Cost for cache tokens in USD',
               existing_nullable=False)
    op.alter_column('monthly_billing', 'output_token_cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment=None,
               existing_comment='Cost for output tokens in USD',
               existing_nullable=False)
    op.alter_column('monthly_billing', 'input_token_cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment=None,
               existing_comment='Cost for input tokens in USD',
               existing_nullable=False)
    op.alter_column('messages', 'total_tokens',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('messages', 'output_tokens',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('messages', 'input_tokens',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('llm_models', 'cache_token_price',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               comment=None,
               existing_comment='Price per 1M cache tokens',
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('llm_models', 'output_token_price',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               comment=None,
               existing_comment='Price per 1M output tokens',
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('llm_models', 'input_token_price',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               comment=None,
               existing_comment='Price per 1M input tokens',
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('daily_token_usage', 'total_cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment=None,
               existing_comment='Total cost in USD',
               existing_nullable=True)
    op.alter_column('daily_token_usage', 'cache_token_cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment=None,
               existing_comment='Cost for cache tokens in USD',
               existing_nullable=True)
    op.alter_column('daily_token_usage', 'output_token_cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment=None,
               existing_comment='Cost for output tokens in USD',
               existing_nullable=True)
    op.alter_column('daily_token_usage', 'input_token_cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment=None,
               existing_comment='Cost for input tokens in USD',
               existing_nullable=True)
    op.drop_constraint('uq_conversation_document', 'conversation_documents', type_='unique')
    op.create_unique_constraint(op.f('uq_chatbot_configs_tenant_name'), 'chatbot_configs', ['tenant_id', 'name'], postgresql_nulls_not_distinct=False)
    op.add_column('api_keys', sa.Column('secret', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###

