"""add_identity_to_heatmap_aggregate_id

``heatmap_aggregate.id`` was created as a plain ``BigInteger`` column (see
``20260710_000001_add_heatmap_ingest_schema.py``) with no sequence/identity.
The model (``app/models/heatmap_aggregate.py``) was later given
``id = Column(BigInteger, Identity(), nullable=False)``, so SQLAlchemy omits
``id`` from INSERT statements expecting Postgres to generate it -- but the
live column was never actually altered to back that, so every insert hits
``NotNullViolationError``.

Hand-written DDL: ``alembic revision --autogenerate`` does not detect this
drift (and separately proposes dropping the unrelated LangGraph checkpoint
tables from environment drift), so it was discarded rather than reviewed.

Idempotent: environments that created the table via
``Base.metadata.create_all()`` *after* the model gained ``Identity()``
already have ``GENERATED BY DEFAULT AS IDENTITY`` on ``id``. Re-adding it
raises ``column ... already has a default value``, so the migration queries
``pg_attribute.attidentity`` first and becomes a no-op when the identity is
already present.

Revision ID: 37b2c8775864
Revises: 36a93d1cb72e
Create Date: 2026-08-24 12:01:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '37b2c8775864'
down_revision: Union[str, None] = '36a93d1cb72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # BY DEFAULT (not ALWAYS) matches Identity()'s default `always=False`,
    # so an explicit id can still be supplied if ever needed. The table is
    # empty in every environment this has shipped to, so there are no
    # existing id values to reconcile with a sequence.
    bind = op.get_bind()

    # '' = no identity, 'd' = GENERATED BY DEFAULT, 'a' = GENERATED ALWAYS.
    attidentity = bind.execute(
        sa.text(
            "SELECT attidentity FROM pg_attribute "
            "WHERE attrelid = 'heatmap_aggregate'::regclass "
            "AND attname = 'id'"
        )
    ).scalar()

    if attidentity:
        # Identity already present (table created via create_all() with the
        # Identity() model). Nothing to do.
        return

    # A plain (non-identity) DEFAULT would also block ADD IDENTITY with the
    # same "already has a default value" error — drop it first if present.
    has_default = bind.execute(
        sa.text(
            "SELECT 1 FROM pg_attrdef "
            "WHERE adrelid = 'heatmap_aggregate'::regclass "
            "AND adnum = (SELECT attnum FROM pg_attribute "
            "            WHERE attrelid = 'heatmap_aggregate'::regclass "
            "            AND attname = 'id')"
        )
    ).first()

    if has_default:
        op.execute("ALTER TABLE heatmap_aggregate ALTER COLUMN id DROP DEFAULT")

    op.execute(
        "ALTER TABLE heatmap_aggregate "
        "ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"
    )


def downgrade() -> None:
    op.execute("ALTER TABLE heatmap_aggregate ALTER COLUMN id DROP IDENTITY IF EXISTS")
