"""add_identity_to_heatmap_aggregate_id

``heatmap_aggregate.id`` was created as a plain ``BigInteger`` column (see
``20260710_000001_add_heatmap_ingest_schema.py``) with no sequence/identity.
The model (``app/models/heatmap_aggregate.py``) was later given
``id = Column(BigInteger, Identity(), nullable=False)``, so SQLAlchemy omits
``id`` from INSERT statements expecting Postgres to generate it -- but the
live column was never actually altered to back that, so every insert hits
``NotNullViolationError``.

Hand-written DDL: ``alembic revision --autogenerate`` does not detect this
drift (and separately proposes dropping the unrelated LangGraph checkpoint
tables from environment drift), so it was discarded rather than reviewed.

Revision ID: 37b2c8775864
Revises: e555c8a175ee
Create Date: 2026-08-24 12:01:00.000000

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '37b2c8775864'
down_revision: Union[str, None] = '36a93d1cb72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # BY DEFAULT (not ALWAYS) matches Identity()'s default `always=False`,
    # so an explicit id can still be supplied if ever needed. The table is
    # empty in every environment this has shipped to, so there are no
    # existing id values to reconcile with a sequence.
    op.execute(
        "ALTER TABLE heatmap_aggregate "
        "ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"
    )


def downgrade() -> None:
    op.execute("ALTER TABLE heatmap_aggregate ALTER COLUMN id DROP IDENTITY IF EXISTS")
