"""remove_tenant_id_from_llm_models

Revision ID: 7336236c2751
Revises: 01773233c655
Create Date: 2026-01-01 11:47:56.419119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7336236c2751'
down_revision: Union[str, None] = '01773233c655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_conversation_document', 'conversation_documents', ['conversation_id', 'document_id'])
    op.drop_constraint(op.f('llm_models_tenant_id_fkey'), 'llm_models', type_='foreignkey')
    op.drop_column('llm_models', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_models', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('llm_models_tenant_id_fkey'), 'llm_models', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_conversation_document', 'conversation_documents', type_='unique')
    # ### end Alembic commands ###

