"""add_document_processing

Revision ID: 04d537f99d07
Revises: aa6f53e5fff9
Create Date: 2025-10-06 17:59:11.554858

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04d537f99d07"
down_revision: str | None = "aa6f53e5fff9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create enum types first (only if they don't exist)
    conn = op.get_bind()

    # Check and create processingstatus enum
    result = conn.execute(
        sa.text("SELECT 1 FROM pg_type WHERE typname = 'processingstatus'")
    )
    if not result.fetchone():
        processingstatus_enum = postgresql.ENUM(
            "PENDING",
            "PROCESSING",
            "COMPLETED",
            "FAILED",
            name="processingstatus",
            create_type=False,
        )
        processingstatus_enum.create(conn, checkfirst=False)

    # Check and create jobstatus enum
    result = conn.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'jobstatus'"))
    if not result.fetchone():
        jobstatus_enum = postgresql.ENUM(
            "PENDING",
            "PROCESSING",
            "COMPLETED",
            "FAILED",
            "CANCELLED",
            name="jobstatus",
            create_type=False,
        )
        jobstatus_enum.create(conn, checkfirst=False)

    op.create_table(
        "document_processing_jobs",
        sa.Column("document_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="jobstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("processor_type", sa.String(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("chunks_created", sa.Integer(), nullable=False),
        sa.Column("processing_time_seconds", sa.Float(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_processing_jobs_document_id"),
        "document_processing_jobs",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_processing_jobs_id"),
        "document_processing_jobs",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_processing_jobs_status"),
        "document_processing_jobs",
        ["status"],
        unique=False,
    )
    # Skip creating uq_conversation_document - it already exists from previous migration
    
    # Check which columns already exist in documents table
    inspector = sa.inspect(conn)
    doc_columns = [col['name'] for col in inspector.get_columns('documents')]
    
    if 'tenant_id' not in doc_columns:
        op.add_column("documents", sa.Column("tenant_id", sa.BigInteger(), nullable=False))
    
    if 'document_type' not in doc_columns:
        op.add_column("documents", sa.Column("document_type", sa.String(), nullable=False))
    
    # Handle processing_status column - might exist as VARCHAR from bootstrap migration
    if 'processing_status' in doc_columns:
        # Drop the old VARCHAR column if it exists
        op.execute("ALTER TABLE documents DROP COLUMN IF EXISTS processing_status CASCADE")
    
    # Add processing_status as ENUM
    op.add_column(
        "documents",
        sa.Column(
            "processing_status",
            postgresql.ENUM(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="processingstatus",
                create_type=False,
            ),
            nullable=False,
        ),
    )
    
    if 'chunk_count' not in doc_columns:
        op.add_column("documents", sa.Column("chunk_count", sa.Integer(), nullable=False))
    
    if 'file_size_bytes' not in doc_columns:
        op.add_column(
            "documents", sa.Column("file_size_bytes", sa.Integer(), nullable=True)
        )
    
    if 'error_message' not in doc_columns:
        op.add_column("documents", sa.Column("error_message", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_documents_processing_status"),
        "documents",
        ["processing_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documents_tenant_id"), "documents", ["tenant_id"], unique=False
    )
    op.create_foreign_key(
        None, "documents", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "tenant_configs", sa.Column("chunk_size", sa.BigInteger(), nullable=False)
    )
    op.add_column(
        "tenant_configs", sa.Column("chunk_overlap", sa.BigInteger(), nullable=False)
    )
    op.add_column(
        "tenant_configs", sa.Column("vector_store_type", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenant_configs", "vector_store_type")
    op.drop_column("tenant_configs", "chunk_overlap")
    op.drop_column("tenant_configs", "chunk_size")
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_index(op.f("ix_documents_tenant_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_processing_status"), table_name="documents")
    op.drop_column("documents", "error_message")
    op.drop_column("documents", "file_size_bytes")
    op.drop_column("documents", "chunk_count")
    op.drop_column("documents", "processing_status")
    op.drop_column("documents", "document_type")
    op.drop_column("documents", "tenant_id")
    # Skip dropping uq_conversation_document - it's managed by other migrations
    op.drop_index(
        op.f("ix_document_processing_jobs_status"),
        table_name="document_processing_jobs",
    )
    op.drop_index(
        op.f("ix_document_processing_jobs_id"), table_name="document_processing_jobs"
    )
    op.drop_index(
        op.f("ix_document_processing_jobs_document_id"),
        table_name="document_processing_jobs",
    )
    op.drop_table("document_processing_jobs")

    # Drop enum types
    processingstatus_enum = postgresql.ENUM(
        "PENDING", "PROCESSING", "COMPLETED", "FAILED", name="processingstatus"
    )
    processingstatus_enum.drop(op.get_bind(), checkfirst=True)

    jobstatus_enum = postgresql.ENUM(
        "PENDING", "PROCESSING", "COMPLETED", "FAILED", "CANCELLED", name="jobstatus"
    )
    jobstatus_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
