"""sync models to ERD

Revision ID: 0ccc8288ae0a
Revises:
Create Date: 2025-09-26 14:44:37.207606

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ccc8288ae0a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_models_id"), "models", ["id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "tenants",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_domain"), "tenants", ["domain"], unique=True)
    op.create_index(op.f("ix_tenants_id"), "tenants", ["id"], unique=False)
    op.create_index(op.f("ix_tenants_name"), "tenants", ["name"], unique=True)
    op.create_table(
        "api_keys",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("secret", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_id"), "api_keys", ["id"], unique=False)
    op.create_index(op.f("ix_api_keys_key"), "api_keys", ["key"], unique=True)
    op.create_table(
        "billing",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("amount", sa.DECIMAL(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_billing_id"), "billing", ["id"], unique=False)
    op.create_table(
        "invitations",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=True),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invitations_email"), "invitations", ["email"], unique=False
    )
    op.create_index(op.f("ix_invitations_id"), "invitations", ["id"], unique=False)
    op.create_index(op.f("ix_invitations_token"), "invitations", ["token"], unique=True)
    op.create_table(
        "tenant_configs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("chat_model_id", sa.BigInteger(), nullable=True),
        sa.Column("embedding_model_id", sa.BigInteger(), nullable=True),
        sa.Column("vec_db_id", sa.BigInteger(), nullable=True),
        sa.Column("search_type", sa.String(), nullable=True),
        sa.Column("threshold_value", sa.Float(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_model_id"],
            ["models.id"],
        ),
        sa.ForeignKeyConstraint(
            ["embedding_model_id"],
            ["models.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["vec_db_id"],
            ["models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tenant_configs_id"), "tenant_configs", ["id"], unique=False
    )
    op.create_table(
        "monitoring",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("tenant_config_id", sa.BigInteger(), nullable=True),
        sa.Column("logs", sa.Text(), nullable=True),
        sa.Column("errors", sa.Text(), nullable=True),
        sa.Column("tokens_count", sa.Text(), nullable=True),
        sa.Column("request_count", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_config_id"], ["tenant_configs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_monitoring_id"), "monitoring", ["id"], unique=False)
    op.create_table(
        "performance_metrics",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("retrieval_recall", sa.Float(), nullable=True),
        sa.Column("llm_eval", sa.Float(), nullable=True),
        sa.Column("bleu", sa.Float(), nullable=True),
        sa.Column("accuracy", sa.Float(), nullable=True),
        sa.Column("precision", sa.Float(), nullable=True),
        sa.Column("f1_score", sa.Float(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("tenant_config_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_config_id"], ["tenant_configs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_performance_metrics_id"), "performance_metrics", ["id"], unique=False
    )
    
    # Check if conversations and documents tables exist before creating dependent tables
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())
    
    # Only proceed if tables exist (for upgrading existing DBs)
    # For fresh databases, these tables will be created by bootstrap migration
    if "conversations" not in existing_tables or "documents" not in existing_tables:
        # Fresh database - skip table creation and modifications
        return
    
    # REMOVED: conversation_documents and feedback table creation moved to separate migration
    # to avoid foreign key dependency issues on fresh databases
    
    # Be tolerant on fresh DBs where index/table may not exist
    op.execute("DROP INDEX IF EXISTS ix_messages_id")
    op.execute("DROP TABLE IF EXISTS messages CASCADE")
    op.add_column(
        "conversations", sa.Column("message_history", sa.JSON(), nullable=True)
    )
    op.add_column(
        "conversations", sa.Column("tenant_id", sa.BigInteger(), nullable=False)
    )
    op.alter_column(
        "conversations",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "conversations",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_constraint(
        op.f("conversations_user_id_fkey"), "conversations", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "conversations", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "conversations", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("conversations", "description")
    op.drop_column("conversations", "title")
    op.add_column("documents", sa.Column("name", sa.String(), nullable=False))
    op.add_column("documents", sa.Column("doc_id", sa.String(), nullable=False))
    op.add_column("documents", sa.Column("s3_url", sa.String(), nullable=True))
    op.alter_column(
        "documents",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_index(op.f("ix_documents_doc_id"), "documents", ["doc_id"], unique=True)
    op.create_index(op.f("ix_documents_s3_url"), "documents", ["s3_url"], unique=True)
    op.drop_constraint(op.f("documents_owner_id_fkey"), "documents", type_="foreignkey")
    op.drop_column("documents", "file_path")
    op.drop_column("documents", "doc_metadata")
    op.drop_column("documents", "file_type")
    op.drop_column("documents", "processing_status")
    op.drop_column("documents", "title")
    op.drop_column("documents", "content")
    op.drop_column("documents", "embedding_model")
    op.drop_column("documents", "chunk_count")
    op.drop_column("documents", "owner_id")
    op.drop_column("documents", "file_size")
    # Add new columns (initially nullable where backfill is required)
    op.add_column("users", sa.Column("tenant_id", sa.BigInteger(), nullable=True))
    op.add_column("users", sa.Column("name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("password_hash", sa.String(), nullable=True))
    op.add_column("users", sa.Column("role_id", sa.BigInteger(), nullable=True))

    # Backfill tenant_id and password_hash for existing rows
    bind = op.get_bind()
    # Ensure a default tenant exists (idempotent)
    tenant_id = bind.execute(
        sa.text(
            """
        INSERT INTO tenants (name, domain, created_at, updated_at)
        VALUES (:name, :domain, NOW(), NOW())
        ON CONFLICT (domain) DO NOTHING
        RETURNING id
        """
        ),
        {"name": "Default Tenant", "domain": "default.local"},
    ).scalar()
    if tenant_id is None:
        tenant_id = bind.execute(
            sa.text("SELECT id FROM tenants WHERE domain = :domain"),
            {"domain": "default.local"},
        ).scalar()

    # Set tenant_id for any existing users where NULL
    bind.execute(
        sa.text("UPDATE users SET tenant_id = :tid WHERE tenant_id IS NULL"),
        {"tid": tenant_id},
    )

    # Copy legacy hashed_password into new password_hash column
    bind.execute(
        sa.text(
            "UPDATE users SET password_hash = hashed_password WHERE password_hash IS NULL"
        )
    )

    # Enforce NOT NULL after backfill
    op.alter_column("users", "tenant_id", existing_type=sa.BigInteger(), nullable=False)
    op.alter_column("users", "password_hash", existing_type=sa.String(), nullable=False)
    op.alter_column(
        "users",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('users_id_seq'::regclass)"),
    )
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_foreign_key(
        None, "users", "roles", ["role_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "users", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("users", "full_name")
    op.drop_column("users", "username")
    op.drop_column("users", "is_active")
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "is_superuser")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_superuser", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("full_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.alter_column(
        "users",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('users_id_seq'::regclass)"),
    )
    op.drop_column("users", "role_id")
    op.drop_column("users", "password_hash")
    op.drop_column("users", "name")
    op.drop_column("users", "tenant_id")
    op.add_column(
        "documents",
        sa.Column("file_size", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "documents",
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "documents",
        sa.Column("chunk_count", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "documents",
        sa.Column("embedding_model", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "documents",
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "documents",
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "documents",
        sa.Column(
            "processing_status", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "documents",
        sa.Column("file_type", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "documents",
        sa.Column(
            "doc_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "documents",
        sa.Column("file_path", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("documents_owner_id_fkey"), "documents", "users", ["owner_id"], ["id"]
    )
    op.drop_index(op.f("ix_documents_s3_url"), table_name="documents")
    op.drop_index(op.f("ix_documents_doc_id"), table_name="documents")
    op.alter_column(
        "documents",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("documents", "s3_url")
    op.drop_column("documents", "doc_id")
    op.drop_column("documents", "name")
    op.add_column(
        "conversations",
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "conversations",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "conversations", type_="foreignkey")
    op.drop_constraint(None, "conversations", type_="foreignkey")
    op.create_foreign_key(
        op.f("conversations_user_id_fkey"),
        "conversations",
        "users",
        ["user_id"],
        ["id"],
    )
    op.alter_column(
        "conversations",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "conversations",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("conversations", "tenant_id")
    op.drop_column("conversations", "message_history")
    op.create_table(
        "messages",
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("context_documents", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("conversation_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("messages_conversation_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("messages_pkey")),
    )
    op.create_index(op.f("ix_messages_id"), "messages", ["id"], unique=False)
    # REMOVED: feedback and conversation_documents dropped in separate migration
    op.drop_index(op.f("ix_performance_metrics_id"), table_name="performance_metrics")
    op.drop_table("performance_metrics")
    op.drop_index(op.f("ix_monitoring_id"), table_name="monitoring")
    op.drop_table("monitoring")
    op.drop_index(op.f("ix_tenant_configs_id"), table_name="tenant_configs")
    op.drop_table("tenant_configs")
    op.drop_index(op.f("ix_invitations_token"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_id"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_email"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_index(op.f("ix_billing_id"), table_name="billing")
    op.drop_table("billing")
    op.drop_index(op.f("ix_api_keys_key"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_tenants_name"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_id"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_domain"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_models_id"), table_name="models")
    op.drop_table("models")
    # ### end Alembic commands ###
