"""add_chat_consumers_table_and_update_conversations

Revision ID: 646f96ed069e
Revises: 20251014_perf_knobs
Create Date: 2025-10-17 15:07:02.797603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '646f96ed069e'
down_revision: Union[str, None] = '20251014_perf_knobs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_consumers',
    sa.Column('chat_consumer_uuid', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Idempotent index creation
    op.execute('CREATE UNIQUE INDEX IF NOT EXISTS ix_chat_consumers_chat_consumer_uuid ON chat_consumers (chat_consumer_uuid)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_chat_consumers_id ON chat_consumers (id)')
    # Be idempotent: index might not exist in some environments
    op.execute("DROP INDEX IF EXISTS ix_citations_message_id")
    # Skip creating unique constraint as it already exists
    op.add_column('conversations', sa.Column('chat_consumer_id', sa.BigInteger(), nullable=True))
    op.alter_column('conversations', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.execute('CREATE INDEX IF NOT EXISTS ix_conversations_id ON conversations (id)')
    op.create_foreign_key(None, 'conversations', 'chat_consumers', ['chat_consumer_id'], ['id'], ondelete='CASCADE')
    # Add check constraint to ensure either user_id OR chat_consumer_id is set (not both)
    op.create_check_constraint(
        'ck_conversations_user_or_chat_consumer',
        'conversations',
        '(user_id IS NOT NULL AND chat_consumer_id IS NULL) OR (user_id IS NULL AND chat_consumer_id IS NOT NULL)'
    )
    # Be idempotent: column may not exist in some environments
    op.execute('ALTER TABLE conversations DROP COLUMN IF EXISTS message_history')
    op.execute('CREATE INDEX IF NOT EXISTS ix_documents_id ON documents (id)')
    # Be idempotent: indexes might not exist in some environments
    op.execute('DROP INDEX IF EXISTS ix_messages_conversation_id')
    op.execute('DROP INDEX IF EXISTS ix_messages_created_at')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # Be idempotent: constraint might not exist in some environments
    op.execute('ALTER TABLE users DROP CONSTRAINT IF EXISTS users_email_key')
    op.execute('CREATE INDEX IF NOT EXISTS ix_users_id ON users (id)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.add_column('conversations', sa.Column('message_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint('ck_conversations_user_or_chat_consumer', 'conversations', type_='check')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.alter_column('conversations', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('conversations', 'chat_consumer_id')
    # Skip dropping unique constraint as it should remain
    op.create_index('ix_citations_message_id', 'citations', ['message_id'], unique=False)
    op.drop_index(op.f('ix_chat_consumers_id'), table_name='chat_consumers')
    op.drop_index(op.f('ix_chat_consumers_chat_consumer_uuid'), table_name='chat_consumers')
    op.drop_table('chat_consumers')
    # ### end Alembic commands ###

