"""add_document_processing_stages_table

Revision ID: b780070b26ff
Revises: 40298b45c576
Create Date: 2025-10-09 17:55:08.929125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b780070b26ff'
down_revision: Union[str, None] = '40298b45c576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_processing_stages',
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.Enum('PENDING', 'DOWNLOADING', 'EXTRACTING', 'CHUNKING', 'EMBEDDING', 'STORING', 'COMPLETED', 'FAILED', name='processingstage'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'RETRYING', name='stagestatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('input_size', sa.Integer(), nullable=True),
    sa.Column('output_size', sa.Integer(), nullable=True),
    sa.Column('stage_metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['document_processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_processing_stages_document_id'), 'document_processing_stages', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_processing_stages_id'), 'document_processing_stages', ['id'], unique=False)
    op.create_index(op.f('ix_document_processing_stages_job_id'), 'document_processing_stages', ['job_id'], unique=False)
    op.create_index(op.f('ix_document_processing_stages_stage'), 'document_processing_stages', ['stage'], unique=False)
    op.create_index(op.f('ix_document_processing_stages_status'), 'document_processing_stages', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_processing_stages_status'), table_name='document_processing_stages')
    op.drop_index(op.f('ix_document_processing_stages_stage'), table_name='document_processing_stages')
    op.drop_index(op.f('ix_document_processing_stages_job_id'), table_name='document_processing_stages')
    op.drop_index(op.f('ix_document_processing_stages_id'), table_name='document_processing_stages')
    op.drop_index(op.f('ix_document_processing_stages_document_id'), table_name='document_processing_stages')
    op.drop_table('document_processing_stages')
    # ### end Alembic commands ###

